### ISSUE TITLE
Where can I find the command run by kulala?

### ISSUE THREAD

**Issue by franroa** [mistweaverco/kulala.nvim#101]
Hi there, I having troubles with Kulala, indeed it can do GET calls, but for some reasons the POST is not working. I set debug to true but I see no errors. 
Is there a way to see the plain cal in logs or something like that?

Thank you in advance!

**Comment by gorillamoe** [comment]
Have you tried to copy the request as curl command to your clipboard?

https://kulala.mwco.app/docs/usage/public-methods#copy

**Comment by franroa** [comment]
oh didnt know it. Thanks!
