### ISSUE TITLE
Having issues trying to open the scratchpad

### ISSUE THREAD

**Issue by Auha** [mistweaverco/kulala.nvim#105]
Here is the error that I receive when I try to open the scratchpad.
```
E5108: Error executing lua: /xxx/lazy/kulala.lua:11: attempt to call field 'scratchpad' (a nil value)      
```

My configuration is very default and the keymaping that I am using for it is the following. 

```
vim.keymap.set("n", "<leader>ks", function()
  require('kulala').scratchpad()
end)
```

Let me know if I'm missing anything.

**Comment by gorillamoe** [comment]
Have you told lazy.nvim about the `keys`? https://lazy.folke.io/spec#spec-lazy-loading

Seems as if the plugin is not yet loaded and you need to tell lazy that when you press certain keys that you want to load kulala.

**Comment by Auha** [comment]
I believe that I am setting it correctly. 

I put in the following:

```
keys = {
    {"<leader>ks", ":lua require('kulala').scratchpad()<CR>"},
  },
```

And I still get similar error. `E5108: Error executing lua [string ":lua"]:1: attempt to call field 'scratchpad' (a nil value)   `

I am able to run the other commands, as lon gas I am on a `*.http` file.

**Comment by gorillamoe** [comment]
What version of Kulala are you using?

**Comment by Auha** [comment]
It says its off of the main branch. So I assume its the latest version.... I have a feeling its a "works for me not for you" situation here.

**Comment by gorillamoe** [comment]
What it is the output of `:lua require("kulala").version()`?

**Comment by Auha** [comment]
Version 2.8.2 

Hmmm I wonder why it didn't go to latest version when I installed it.

I just forced update it and it works correctly.
