### ISSUE TITLE
Allow spaces in query

### ISSUE THREAD

**Issue by Grueslayer** [mistweaverco/kulala.nvim#111]
Query lines like

`GET {{baseURL}}/v2.0/companies?tenant=default&$filter=name eq 'CompanyX'&$select=id HTTP/1.1`

can not be used because the line is splitted by Space (but later Spaces are correctly URL encoded in code)

**Comment by Grueslayer** [comment]
fixed by #110

**Comment by gorillamoe** [comment]
Is in main now, will prepare a release this evening.
