### ISSUE TITLE
Unable to run multiple request.

### ISSUE THREAD

**Issue by Muizzyranking** [mistweaverco/kulala.nvim#112]
I do not know if this is a bug or incorrect set up, if i have multiple HTTP requests in a file, only the first one is being ran. 

I will attach some picture to explain what I am saying.

Note the virtual text after the request, shows i ran the first request, also note the response

![image](https://github.com/user-attachments/assets/e3d276f5-4fe8-4a4c-a018-e0b855dbb160)

Now see the next request is sent, the response is the same with the first even tho it showed that the request was sent

![image](https://github.com/user-attachments/assets/e644a412-4c30-4011-9831-9e28f2214c7b)

Now, i changed it and made the second request first and ran it, this time, the response changed

![image](https://github.com/user-attachments/assets/b9a3d9cc-3a2c-4dc9-8f02-8032f313b7ad)

Now, when i ran the second, it still shows the response

![image](https://github.com/user-attachments/assets/2f1fa7f8-f6f4-43c8-bb0b-dbd36b8564d5)

The only thing i changed is the icons, this is my config
```lua
vim.filetype.add({
  extension = {
    ["http"] = "http",
  },
})
return {
  "mistweaverco/kulala.nvim",
  ft = "http",
  keys = {
    { "<leader>R", "", desc = "+Rest" },
    { "<leader>Rs", "<cmd>lua require('kulala').run()<cr>", desc = "Send the request" },
    { "<leader>Rt", "<cmd>lua require('kulala').toggle_view()<cr>", desc = "Toggle headers/body" },
    { "<leader>Rp", "<cmd>lua require('kulala').jump_prev()<cr>", desc = "Jump to previous request" },
    { "<leader>Rn", "<cmd>lua require('kulala').jump_next()<cr>", desc = "Jump to next request" },
  },
  opts = {},
  config = function()
    require("kulala").setup({
      icons = {
        inlay = {
          loading = " ",
          done = " ",
          error = " ",
        },
      },
    })
  end,
}
```

And no, I am not using lazyvim, I just opened it for reference.

**Comment by gorillamoe** [comment]
That is not a bug, that is by intention.

You need separate these requests by `###`, so separate pdfit would look something like this:

```http

GET https://httpbin.org/get
Accept: application/json

###

GET https://httpbin.org/get
Accept: application/json

###

GET https://httpbin.org/get
Accept: application/json
```

**Comment by Muizzyranking** [comment]
Ohh, I didn't know that. I must have missed that. Thank you, appreciate your response.
