### ISSUE TITLE
JSON response is not formatted correctly

### ISSUE THREAD

**Issue by suinming** [mistweaverco/kulala.nvim#12]
## my system
- OS: Ubuntu 22.04 jammy
- Kernel: x86_64 Linux 6.8.0-76060800daily20240311-generic
- Shell: zsh 5.8.1
- Nvim: v0.10.0
- jq: 1.7
- curl: 7.81.0

## issue
JSON response is not formatted correctly 

![image](https://github.com/mistweaverco/kulala.nvim/assets/86294140/f59c4ae0-b2e4-41c6-bb5f-b1e01bf204a9)

**Comment by gorillamoe** [comment]
Add the `accept: application/json` header to your request and it should be formatted 👍🏾

**Comment by gorillamoe** [comment]
Hey @suinming, does this work for you, can we close this issue?

**Comment by suinming** [comment]
Sorry for the late reply. It solve my issue thanks a lot.

**Comment by gorillamoe** [comment]
No worries, thanks for helping to make Kulala better 👍🏾
