### ISSUE TITLE
Headers with values containing a colon are not parsed correctly

### ISSUE THREAD

**Issue by felixscherz** [mistweaverco/kulala.nvim#121]
Hi, thank you for working on this plugin!

I was playing around with the authorization headers and found that basic auth would not work for me. This is the request I tried:

```
GET http://httpbin.org/basic-auth/foo/bar HTTP/2.1
Authorization: Basic foo:bar
```
Which using `curl -v http://httpbin.org/basic-auth/foo/bar -u foo:bar` should respond with

```json
{
  "authenticated": true,
  "user": "foo"
}
```
I investigated this a bit and found that the headers were not being parsed correctly if the value contained a colon (`:`).
Slightly modifying the regular expression used for parsing the headers fixed the issue for me, I'll submit a pull request in a second :)

**Comment by gorillamoe** [comment]
You're a hero! :heart:! What a great catch! Thanks for your PR! It's already merged into main and will be released soon!
