### ISSUE TITLE
Response processing refactoring

### ISSUE THREAD

**Issue by Grueslayer** [mistweaverco/kulala.nvim#124]
**NEEDS Testing**
**NEEDS proof reading for docs changes**

implemented by #123 

- Filetype from reponses `Content-Type` header:
  Formatting was done using the requests `Accept` header.
  This forces to specify the header and may destroy the respose body when another type is delivered (e.g. 404 HTML eror message).
  (temporary ft.txt will no longer be created)

- Filetype mapping by config: 
  The filetype mapping was fixed for `application/json`, `application/xml` and `text/html` in code.
  A new `contentypes` in the config allows you to define any (like missing `text/xml`) content-type.

- Formatter:
  **Breaking Change** The formatter are now also part of the above `contentypes` section.
  You can define a cmdline (as lua table like before) or newly a lua function with `formatted_body = function(body)` per content-type.

- Request Variables:
  The missing `(request|response).body.*` which gives you the full body as text (e.g. usable for Bearer-Authentications where the bearer comes a plaintext body) was added.
  XPath and JsonPath will no longer be distinguished by the beginning (e.g. `(//*/talent-score)[1]/text()` does nost start with `//` but is still a valid XPath).
  `contentypes` is here used for a per content-type definition, too.
  You can use a lua table for an external program which receives the full body as stdin and has to return the selected value in stdout.
  The placeholder `{{path}}` can be used in any string of this defintion.
  Alternative you can give a lua function of `value = function(body, path)`.

**Comment by gorillamoe** [comment]
Thanks for this impressive PR! :heart: :heart_eyes:. You're an asset to this project!!!

**Comment by gorillamoe** [comment]
My test files all still work, even if I remove the accept header. My production files also still work. What a wonderful job you did!

I released it into the wild (v3.0.0). Thanks again!
