### ISSUE TITLE
Errors related to `CONFIG.get().*` methods

### ISSUE THREAD

**Issue by ahmedelgabri** [mistweaverco/kulala.nvim#140]
I'm getting errors for these 

- `CONFIG.get().additional_curl_options` returns `nil` here https://github.com/mistweaverco/kulala.nvim/blob/601bf6f4ba7ffb34d3b3480982d8123a9c89bae4/lua/kulala/parser/init.lua#L423

- CONFIG.get().contenttypes[content_type] returns `nil` here https://github.com/mistweaverco/kulala.nvim/blob/601bf6f4ba7ffb34d3b3480982d8123a9c89bae4/lua/kulala/internal_processing/init.lua#L50

Testing with this

```http
GET https://httpbin.org/get HTTP/1.1
content-type: application/json
accept: application/json
```

And this is my `lazy.nvim` config

```lua
{ 'https://github.com/mistweaverco/kulala.nvim', ft = 'http' }
```

and inside `ftplugin/http.lua`

```lua
vim.keymap.set({ 'n' }, '<CR>', function() require('kulala').run() end, { remap = true, desc = 'Run current HTTP request' })
```

**Comment by gorillamoe** [comment]
You have to call `.setup()` even if its empty.

See: https://github.com/mistweaverco/kulala.nvim?tab=readme-ov-file#configuration

**Comment by ahmedelgabri** [comment]
Did this change recently, because it was working before? Anyway, that was it, thanks!
