### ISSUE TITLE
Accessing cookies present in the response headers

### ISSUE THREAD

**Issue by pdonadeo** [mistweaverco/kulala.nvim#148]
In some cases, in the authentication flow, it is necessary to access the cookies set by the login response, e.g. the session cookie or the CSRF cookie.

It would be nice to be able to access the value of the cookies the same way you access the other headers, something like: `REQUEST_ONE.response.cookies['sessionid']`.

Do you think it is possible in the future to have this feature?

**Comment by gorillamoe** [comment]
https://github.com/mistweaverco/kulala.nvim/releases/tag/v3.4.0

https://kulala.mwco.app/docs/usage/request-variables#special-case-for-cookies

Thanks for the great idea!

**Comment by pdonadeo** [comment]
@gorillamoe Thank you for implementing this feature so quickly!

**Comment by pdonadeo** [comment]
This plugin should be illegal because of how convenient it is!
