### ISSUE TITLE
Display selected environment in statusbar

### ISSUE THREAD

**Issue by t-eichmann** [mistweaverco/kulala.nvim#16]
Once the selection of environments from #15 is implemented it would be nice to have the possibility to display the currently selected environment in the statusbar.

**Comment by gorillamoe** [comment]
Basic support for lualine is here:

```lua
require('lualine').setup({
  sections = {
    lualine_a = {},
    lualine_b = {},
    lualine_c = { "filename" },
    lualine_x = { "kulala", "encoding", "fileformat", "branch"},
    lualine_y = { "progress" },
    lualine_z = { "location" }
  },
})

```

**Comment by gorillamoe** [comment]
Screenshot

![image](https://github.com/mistweaverco/kulala.nvim/assets/1384938/826fc2fe-144e-45a4-a34c-044251ff03d3)
