### ISSUE TITLE
Unable to call rest API on neovim 0.10

### ISSUE THREAD

**Issue by sangramsingha** [mistweaverco/kulala.nvim#17]
Hi 

While trying to call API mentioned in [usage.md](https://github.com/mistweaverco/kulala.nvim/blob/main/docs/usage.md) got error.

![image](https://github.com/mistweaverco/kulala.nvim/assets/30252302/10605784-99df-41c9-9df8-1fe575ca2bff)

Specs:
Neovim 0.10
OS : Linux Mint 21.3

![image](https://github.com/mistweaverco/kulala.nvim/assets/30252302/c4a2835e-e00c-450a-8279-cd662308cea0)
![image](https://github.com/mistweaverco/kulala.nvim/assets/30252302/d699f8c1-3448-400e-ba77-34f0d9c370d8)

**Comment by gorillamoe** [comment]
Strange :thinking: is this reproducable? I feel that the pokeapi is sometimes flaky, but I should catch those errors then..

**Comment by gorillamoe** [comment]
Uhm, just to be safe, you have cURL installed, right?

**Comment by gorillamoe** [comment]
Can you try with this?

```http
GET https://api.predic8.de/shop/v2/products
accept: application/json
```

**Comment by gorillamoe** [comment]
I pushed a fix, can you try the latest main or v1.2.1?

**Comment by sangramsingha** [comment]
Thanks a lot for such prompt response. 
It is working now. 

![image](https://github.com/mistweaverco/kulala.nvim/assets/30252302/b8167ee7-2f72-4442-9d6c-b70cfb2a4dd2)

**Comment by gorillamoe** [comment]
You're welcome, make sure to install `jq` so the JSON output gets beautifully formatted.
