### ISSUE TITLE
[Feature Request] Breakdown of time to execute request

### ISSUE THREAD

**Issue by sanchay9** [mistweaverco/kulala.nvim#180]
can we show breakdown of time taken to execute the request similar to what postman shows:

![image](https://github.com/user-attachments/assets/b673c672-ec7d-4ab7-b0b0-f63ea56c7cf7)

This article shows how the get the times: https://blog.josephscott.org/2011/10/14/timing-details-with-curl/

**Comment by gorillamoe** [comment]
Indeed a cool 😎 feature! Will implement!
