### ISSUE TITLE
Get the currently selected env?

### ISSUE THREAD

**Issue by mumahmud** [mistweaverco/kulala.nvim#185]
Awesome plugin! Been setting up my frequently used Postman requests locally thanks to this.

I know how to select envs using `lua require('kulala').set_selected_env()` but is there a method to get the currently selected env? I wanted to put that value in the statusline just so I can quickly check what env I am currently working on.

**Comment by gorillamoe** [comment]
```lua
require('kulala').get_selected_env() 
```

is now in main :+1:
