### ISSUE TITLE
[Feature UI] Add console in winbar

### ISSUE THREAD

**Issue by iamxiaojianzheng** [mistweaverco/kulala.nvim#188]
```http
POST https://jsonplaceholder.typicode.com/posts
Content-Type: application/json; charset=utf-8

{"title":"中文"}

> {%
client.log(response.body.title)
%}
```

Hope to add a `Console` panel to view the print output from `pre-request` and `post-request`.

![image](https://github.com/user-attachments/assets/79e52c2d-324b-4d0a-aeca-29b3d27242e3)

Related to https://github.com/mistweaverco/kulala.nvim/issues/176

**Comment by gorillamoe** [comment]
Why'd you close the PR?
