### ISSUE TITLE
Empty response when use variable

### ISSUE THREAD

**Issue by tknightz** [mistweaverco/kulala.nvim#20]
It happens when I use variable in the url, check the screenshot below. (It works fine without variable)

![image](https://github.com/mistweaverco/kulala.nvim/assets/40225276/c10332c4-654d-4de7-8398-f08b02ed02ee)

My config is copied from the docs:
```
  {
    "mistweaverco/kulala.nvim",
    ft = "http",
    config = function()
      require("kulala").setup({
        default_view = "body",
        default_env = "dev",
        debug = false,
      })
    end,
  },
```

curl, wget and jq are installed.

**Comment by gorillamoe** [comment]
When I'm done with the rewrite, your example should also work. Until then, this here should work:

```http
GET {{host}}/api/v2/pokemon/ditto HTTP/1.0
accept: application/json
```

**Comment by tknightz** [comment]
That's quick! Ok, I need to put the `https://` part to the variable to make it work.

```
@host="https://pokeapi.co/api/v2"

GET {{host}}/api/v2/pokemon/ditto HTTP/1.0
accept: application/json
```
