### ISSUE TITLE
Query error at 20:6. Invalid node type "res_redirect":

### ISSUE THREAD

**Issue by vyskocilm** [mistweaverco/kulala.nvim#223]
After 2cdc64d6c494af3bbee2be44218cc105ad43e8f9 I get this error when starting neovim. cc @treywood 

```
Failed to run `config` for kulala.nvim

/usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252: Query error at 20:6. Invalid node type "res_redirect":
    (res_redirect
     ^

# stacktrace:                                                                                                                                         
  - /usr/share/nvim/runtime/lua/vim/treesitter/query.lua:252 _in_ **fn**
  - /usr/share/nvim/runtime/lua/vim/func/_memoize.lua:58 _in_ **parse**
  - lua/kulala/parser/treesitter.lua:15
  - lua/kulala/parser/init.lua:11
  - lua/kulala/ui/init.lua:6
  - lua/kulala/init.lua:1
  - ~/.config/nvim/lua/plugins/kulala.lua:9 _in_ **config**
  - /usr/share/nvim/runtime/filetype.lua:36
  - /usr/share/nvim/runtime/filetype.lua:35
```

I tried fixing it via reinstalling TS syntax for `http`, but it haven't helped and `:TSUpdate` says all parsers are up to date.

```
Installation ~
- OK `tree-sitter` found 0.22.6 (parser generator, only needed for :TSInstallFromGrammar)
- OK `node` found v22.3.0 (only needed for :TSInstallFromGrammar)
- OK `git` executable found.
- OK `cc` executable found. Selected from { vim.NIL, "cc", "gcc", "clang", "cl", "zig" }
  Version: cc (SUSE Linux) 14.2.0
- OK Neovim was compiled with tree-sitter runtime ABI version 14 (required >=13). Parsers must be compatible with runtime ABI.

Parser/Features         H L F I J
  - http                ✓ . . . ✓
```

Removing lines with `(res_redirect` fixed the problem for me. Because `http.so` does not have a symbol  `res_redirect` this probably require a modified version of a HTTP treesitter plugin.

```sh
> strings ~/.local/share/nvim/lazy/nvim-treesitter/parser/http.so  | grep res_redirect
```

**Comment by gorillamoe** [comment]
Weird, doesn't happen to me, do you have treesitter enabled for Kulala via treesitter= true option?

**Comment by treywood** [comment]
this was added to the http tree-sitter parser last week (https://github.com/rest-nvim/tree-sitter-http/pull/40), you should make sure that your parsers are up to date with `:TSUpdate`. I'll also work on a change to make these queries lazily parsed so that this doesn't affect people who haven't turned on tree-sitter parsing

**Comment by vyskocilm** [comment]
> you should make sure that your parsers are up to date with :TSUpdate

`:Lazy update nvim-treesitter` was needed too. Thanks for a help!
