### ISSUE TITLE
More than one request no longer working (when having lines that start with spaces)

### ISSUE THREAD

**Issue by Alt-iOS** [mistweaverco/kulala.nvim#236]
In this file

```http
GET http://localhost:3000/backups
###
 
GET http://localhost:3000/backups/new

```

Calling the second request results in the following error 

```lua
  Error  22:45:52 msg_show.lua_error Error executing vim.schedule lua callback: ...local/share/nvim/lazy/kulala.nvim/lua/kulala/db/init.lua:41: scoped variable: Invalid buffer id: 517
stack traceback:
	[C]: in function '__newindex'
	...local/share/nvim/lazy/kulala.nvim/lua/kulala/db/init.lua:41: in function 'save_data'
	...local/share/nvim/lazy/kulala.nvim/lua/kulala/db/init.lua:64: in function 'update'
	...al/share/nvim/lazy/kulala.nvim/lua/kulala/parser/env.lua:16: in function 'get_env'
	...l/share/nvim/lazy/kulala.nvim/lua/kulala/parser/init.lua:492: in function 'parse'
	...ocal/share/nvim/lazy/kulala.nvim/lua/kulala/cmd/init.lua:88: in function 'run_parser'
	...local/share/nvim/lazy/kulala.nvim/lua/kulala/ui/init.lua:203: in function <...local/share/nvim/lazy/kulala.nvim/lua/kulala/ui/init.lua:192>
```
Nonetheless if I put the second request at the top of the file, it does work.

This is my nvim version 
```
NVIM v0.10.1
Build type: Release
LuaJIT 2.1.1725453128
```
OS is mac 14.6.1

and Kulala is latest HEAD

**Comment by gorillamoe** [comment]
you have an line with a space here

![image](https://github.com/user-attachments/assets/cd1ef7fd-7ead-4db7-8a98-b0d6beff44b5)

that's confusing the parser (with a recent change, that fixed a lot of other stuff).

the first non empty line (which does not start with a `#` after a new block start (`###`) is considered the "request line" where you have the [VERB] [URL] [VERSION?].

Just remove the space and it should work.

**Comment by gorillamoe** [comment]
This is the commit that should have introduced that "now I care about lines starting with spaces": https://github.com/mistweaverco/kulala.nvim/commit/4bc33af4e6a4857c28cb691ee05600fb7912410f

Previously we "trimmed" the lines before checking anything, but that causes trouble when having gql queries.

**Comment by gorillamoe** [comment]
I can recommend this plugin for whitespace handling btw: https://github.com/ntpeters/vim-better-whitespace

**Comment by Grueslayer** [comment]
> I can recommend this plugin for whitespace handling btw: https://github.com/ntpeters/vim-better-whitespace

Vanilla VIM can also do something in that way with special characters `:help listchars`, here `trail` defines a char for trailing whitespaces:

```lua
vim.o.listchars = 'tab:▶·,trail:·,extends:…,precedes:…,nbsp:␣,eol:↲'
```
