### ISSUE TITLE
Add suport for periods in variables

### ISSUE THREAD

**Issue by BurkeStrang** [mistweaverco/kulala.nvim#244]
![image](https://github.com/user-attachments/assets/140c267f-2601-4cf6-a68f-df5e36764317)

| kulala: The variable 'Clients.Api_HostAddress' was not found in the document or in the environment. Returning the string as received ...

**Comment by gorillamoe** [comment]
We mostly adhere to what env vars are designed and defined, so this is by intention:

> Environment variable names used by the utilities in the Shell and Utilities volume of IEEE Std 1003.1-2001 consist solely of uppercase letters, digits, and the '_' (underscore) from the characters defined in Portable Character Set and do not begin with a digit. Other characters may be permitted by an implementation; applications shall tolerate the presence of such names.

We do not enforce all uppercase, or no digit as first char, but other than that no dots allowed.

**Comment by gorillamoe** [comment]
It would even conflict with the way we handle it with dynamic variables based on response: https://kulala.mwco.app/docs/usage/dynamically-setting-environment-variables-based-on-response-json#with-built-in-parser
