### ISSUE TITLE
[Feature Request] Allow passing certificate and key to request

### ISSUE THREAD

**Issue by matbme** [mistweaverco/kulala.nvim#245]
I often need to pass certificates and keys when calling my APIs. Right now, I have to use curl directly with `--cert` and `--key`, but it would be awesome if Kulala supported specifying a path for both files.

Maybe something along the lines of
```http
# @cert <certificate_path>
# @key <key_path>
GET https://example.com
```
similar to how it currently handles naming and external variable parsing.

**Comment by Grueslayer** [comment]
@gorillamoe This is how vscode-rest-client is doing it:

https://github.com/Huachao/vscode-restclient#ssl-client-certificates

**Comment by Grueslayer** [comment]
@matbme You can test using branch `ssl_cert_auth`

**Comment by matbme** [comment]
Hi, thanks for the quick implementation, it worked like a charm!

Would it also be possible to match certificates across multiple subdomains? For example, I would like to share the same certificate across `instanceA.example.com` and `instanceB.example.com`.

**Comment by Grueslayer** [comment]
@matbme see last commit to branch

**Comment by matbme** [comment]
Works as well. Thanks!
