### ISSUE TITLE
[Feature Request] Allow specifying host as a header

### ISSUE THREAD

**Issue by igorlfs** [mistweaverco/kulala.nvim#248]
Hello!

rest.nvim has a nice feature: it's possible to specify the host as if it were a header. They call that "[URL without Host](https://github.com/rest-nvim/rest.nvim/blob/main/spec/examples/url_without_host.http)". For instance:

```http
GET /api
HOST: example.com
```

It'd be nice to have that in kulala as well.

**Comment by Grueslayer** [comment]
@igorlfs I don‘t see any use case for this, please explain what advantage you see to put the host directly to the request line or use variables like {host}/api and define @host somewhere.

**Comment by igorlfs** [comment]
> what advantage you see over putting the host directly to the request line or use variables like {host}/api and define @host somewhere.

Indeed, defining a variable solves most use cases (eg, a long URL), and I'd say is the recommend way. However, I've noticed that multiple APIs are documented with examples that already include the `Host`. So, by having this feature, copy-pasting from such examples would be easier.

**Comment by gorillamoe** [comment]
Can you elaborate a bit more? Maybe with some example docs links? I usually work with a lot of different APIs on a daily basis, but never found it hard to copy from their docs into .http 🤷🏾.

I'm really curious 🧐 what these API docs look like.

**Comment by Grueslayer** [comment]
First one has Host: BEFORE request line and not part of header lines….

**Comment by igorlfs** [comment]
Yeah, that was definitely odd

**Comment by gorillamoe** [comment]
I would rather not implement this, because it makes building the curl command a lot harder with little to no benefit.

**Comment by igorlfs** [comment]
> I would rather not implement this

Sure, no problem!

**Comment by dakennguyen** [comment]
Could we please circle back to this? Here in [this document ](https://developer.mozilla.org/en-US/docs/Web/HTTP/Messages#http_requests) they used only the `Host`, and [curlconverter](https://curlconverter.com/http/) also translate curl command into this format. The converter is especially useful since I often have to copy curl command on browser. Otherwise, is there a way to copy API requests on the browser into http format?

**Comment by YaroSpace** [comment]
I think it makes sense, as it is also in the IntelliJ spec.

**Comment by igorlfs** [comment]
Feel free to reopen!
