### ISSUE TITLE
JSON output for other contenttypes than application/json

### ISSUE THREAD

**Issue by svenXY** [mistweaverco/kulala.nvim#255]
Hi,

I'm running against some service that requires quitre specific Accept-Headers like e.g. `Accept:application/vnd.atlas.2024-08-05+json`.

I added some config for that:
```lua
    contenttypes = {
      ["application/vnd.atlas.2024-08-05+json"] = {
        ft = "json",
        formatter = { "jq", "." },
      },
      ["application/json"] = {
        ft = "json",
        formatter = { "jq", "." },
      },
     [...]
```
but this does not seem to change anything - the response body is still detected as ft=text and not rendered.

Furthermore, it seems to be quite odd to have to add contenttypes for each versioned type here. 

Can this be made more userfriendly (i.e. apply application/json for all applicatio/.*+json) or similar?

**Comment by svenXY** [comment]
it also does not format headers properly when setting output to headers_body.

**Comment by svenXY** [comment]
Hi, thanks for the quick reply. The background is here: https://www.mongodb.com/docs/atlas/api/versioned-api-overview/

The response header is (exactly as the Accept-header in the request):
`content-type: application/vnd.atlas.2023-01-01+json;charset=utf-8`

I also tried, what happens when I set application/json instead.

The response then is the following (though nicely formatted):
```json

date: Fri, 04 Oct 2024 12:59:41 GMT
www-authenticate: Digest realm="MMS Public API", domain="", nonce="5INeqXOt2+euBa0xJxxxxxxbcLQM1RfgQI", algorithm=MD5, qop="auth", stale=false
content-type: application/json
content-length: 106
x-envoy-upstream-service-time: 10
server: mdbws

HTTP/2 406 
date: Fri, 04 Oct 2024 12:59:41 GMT
strict-transport-security: max-age=31536000; includeSubdomains;
referrer-policy: strict-origin-when-cross-origin
x-permitted-cross-domain-policies: none
x-content-type-options: nosniff
content-type: application/json
content-length: 140
x-envoy-upstream-service-time: 16
server: mdbws


{
  "detail": "Invalid accept header or version date.",
  "error": 406,
  "errorCode": "INVALID_VERSION_DATE",
  "parameters": [],
  "reason": "Not Acceptable"
}
```

**Comment by Grueslayer** [comment]
Can you explain why we have two Header blocks here, one with 106 bytes and one with 140 bytes?

**Comment by svenXY** [comment]
yes, I believe Digest Authentication is a two-step authentication:
https://en.wikipedia.org/w/index.php?title=Digest_access_authentication&section=7#Example_with_explanation

**Comment by Grueslayer** [comment]
As we've TWO headers seperated by an empty line, I'm not sure we get the "correct" one, but if both contain the same Content-Type it should rendered correctly if config is correct.

Can you please post the original header file (file location can be printed by `:lua print(require("kulala.globals").HEADERS_FILE)`)

**Comment by svenXY** [comment]
HTTP/2 401 
date: Fri, 04 Oct 2024 14:11:36 GMT
www-authenticate: Digest realm="MMS Public API", domain="", nonce="P0x0iqybX5nL52/R2H8FLwPJUToM33Uo", algorithm=MD5, qop="auth", stale=false
content-type: application/json
content-length: 106
x-envoy-upstream-service-time: 10
server: mdbws

HTTP/2 200 
date: Fri, 04 Oct 2024 14:11:36 GMT
strict-transport-security: max-age=31536000; includeSubdomains;
referrer-policy: strict-origin-when-cross-origin
x-permitted-cross-domain-policies: none
x-content-type-options: nosniff
x-mongodb-service-version: gitHash=44fd882f0c35af91d2587927aa18506a4c61dbc2; versionString=v20241002
content-type: application/vnd.atlas.2023-01-01+json;charset=utf-8
x-frame-options: DENY
vary: Accept-Encoding
content-length: 1355
x-envoy-upstream-service-time: 46
server: mdbws

**Comment by svenXY** [comment]
btw., when running against httpbin.io, I get the following (but with proper detection and formatting):

Request:
```
GET https://httpbin.io/digest-auth/auth/user/pass
Authorization: Digest user:pass
Accept:application/json
```

Response(s):
```
HTTP/1.1 401 Unauthorized
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Www-Authenticate: Digest qop=auth, realm="httpbin.io", algorithm=MD5, nonce=4b71421f130e87d04ec05aaf0193f7b2, opaque=14e4303ba14d09fd06591029e207bdc8
Date: Fri, 04 Oct 2024 14:13:18 GMT
Content-Length: 52

HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Date: Fri, 04 Oct 2024 14:13:18 GMT
Content-Length: 43


{
  "authorized": true,
  "user": "user"
}


```

**Comment by svenXY** [comment]
more info:

HTTPie does the following:
```
$ http --verbose --print=HhBbm -A digest -a 'user:pass' --all https://httpbin.io/digest-auth/auth/user/pass
GET /digest-auth/auth/user/pass HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Host: httpbin.io
User-Agent: HTTPie/3.2.3



HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Content-Length: 43
Content-Type: application/json; charset=utf-8
Date: Fri, 04 Oct 2024 14:17:26 GMT

{
    "authorized": true,
    "user": "user"
}
```

and curl:
```
curl https://httpbin.io/digest-auth/auth/user/pass -i --digest --user 'user:pass'
HTTP/1.1 401 Unauthorized
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Www-Authenticate: Digest qop=auth, realm="httpbin.io", algorithm=MD5, nonce=0466467c2af05e1dc3647666a0881e5f, opaque=dace930722adc22226b9b442aa01127f
Date: Fri, 04 Oct 2024 14:18:46 GMT
Content-Length: 52

HTTP/1.1 200 OK
Access-Control-Allow-Credentials: true
Access-Control-Allow-Origin: *
Content-Type: application/json; charset=utf-8
Date: Fri, 04 Oct 2024 14:18:46 GMT
Content-Length: 43

{
  "authorized": true,
  "user": "user"
}
```

so it seems to me that the first 401 response is rather normal

**Comment by Grueslayer** [comment]
Parsing of that "double" header is no problem, currently all lines will be parsed and merged. So the second "Content-Type" will be used:

```lua
{
  ["content-length"] = "1355",
  ["content-type"] = "application/vnd.atlas.2023-01-01+json;charset=utf-8",
  date = "Fri, 04 Oct 2024 14:11:36 GMT",
  ["referrer-policy"] = "strict-origin-when-cross-origin",
  server = "mdbws",
  ["strict-transport-security"] = "max-age=31536000; includeSubdomains;",
  vary = "Accept-Encoding",
  ["www-authenticate"] = 'Digest realm="MMS Public API", domain="", nonce="P0x0iqybX5nL52/R2H8FLwPJUToM33Uo", algorithm=MD5, qop="auth", stale=false',
  ["x-content-type-options"] = "nosniff",
  ["x-envoy-upstream-service-time"] = "46",
  ["x-frame-options"] = "DENY",
  ["x-mongodb-service-version"] = "gitHash=44fd882f0c35af91d2587927aa18506a4c61dbc2; versionString=v20241002",
  ["x-permitted-cross-domain-policies"] = "none"
}
```

And with your `header.txt` everything runs fine on my system using this config

```lua
  {
    'mistweaverco/kulala.nvim',
    config = function()
      require('kulala').setup({
        debug = true,
        vscode_rest_client_environmentvars = true,
        winbar = true,
        default_winbar_panes = { "body", "headers" },
        contenttypes = {
          ["application/vnd.atlas.2023-01-01+json"] = {
            ft = "json",
            formatter = { "jq", "." },
            pathresolver = require("kulala.parser.jsonpath").parse,
          },
        },
      })
      vim.filetype.add({
        extension = {
          ['http'] = 'http',
        },
      })
    end,
  },
```

JSON will be formatted correctly.

Maybe we'll have a problem showing both together because the header.txt file now has two blocks, I can check this later.

Can you have a look using to show the body only or like above winbar with separate displays?

**Comment by gorillamoe** [comment]
> btw., when running against httpbin.io, I get the following (but with proper detection and formatting (header colours etc.)), whereas, with the other contenttype, nothing is formatted (also no colours in the Headers etc.)

I think that is due to the tree-sitter-http grammar :see_no_evil:

**Comment by gorillamoe** [comment]
Can you print the ouput of `:Inspect` (in the not correctly highlighted window) here?

**Comment by svenXY** [comment]
@Grueslayer yes, it works with your config - maybe using config instead of opts did the trick?

@gorillamoe: if you mean in the output window, then the error message is: "No items found at position 0,0 in buffer 7

But I think it's something else as when for example querying httpbin with Digest (see above), we also see two headers and some Response body, but everything is rendered correctly.

It only seems to fail if contenttypes are non-standard

**Comment by svenXY** [comment]
I think the problem was that my opts = ... was not properly laded by lazy.
I now also tried your config with headers_body in the winbar and it also rendered correctly.
