### ISSUE TITLE
error for contenttypes: module 'kulala.parser.jsonpath' not found

### ISSUE THREAD

**Issue by svenXY** [mistweaverco/kulala.nvim#256]
Hi,

when attremptig to set additional contenttypes, require("kulala.parser.jsonpath") fails:
 `pathresolver = require("kulala.parser.jsonpath").parse`
for me throws as soon as I add it to one of the contenttypes

```
Fehler beim Ausführen von "/Users/me/.config/nvim/init.lua":
Failed to load `plugins.kulala`
/Users/me/.config/nvim/lua/plugins/kulala.lua:33: module 'kulala.parser.jsonpath' not found:
	no field package.preload['kulala.parser.jsonpath']
	cache_loader: module 'kulala.parser.jsonpath' not found
	cache_loader_lib: module 'kulala.parser.jsonpath' not found
	no file './kulala/parser/jsonpath.lua'
	no file '/Users/me/dev_other/neovim/.deps/usr/share/luajit-2.1/kulala/parser/jsonpath.lua'
	no file '/usr/local/share/lua/5.1/kulala/parser/jsonpath.lua'
	no file '/usr/local/share/lua/5.1/kulala/parser/jsonpath/init.lua'
	no file '/Users/me/dev_other/neovim/.deps/usr/share/lua/5.1/kulala/parser/jsonpath.lua'
	no file '/Users/me/dev_other/neovim/.deps/usr/share/lua/5.1/kulala/parser/jsonpath/init.lua'
	no file './kulala/parser/jsonpath.so'
	no file '/usr/local/lib/lua/5.1/kulala/parser/jsonpath.so'
	no file '/Users/me/dev_other/neovim/.deps/usr/lib/lua/5.1/kulala/parser/jsonpath.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './kulala.so'
	no file '/usr/local/lib/lua/5.1/kulala.so'
	no file '/Users/me/dev_other/neovim/.deps/usr/lib/lua/5.1/kulala.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
# stacktrace:
  - ~/.config/nvim/lua/plugins/kulala.lua:33 _in_ **load**
  - ~/.config/nvim/lua/user/lazy.lua:28
  - ~/.config/nvim/init.lua:1
```

**Comment by Grueslayer** [comment]
Am 04.10.2024 um 14:48 schrieb Sven Hergenhahn ***@***.***>:﻿
Hi,
when attremptig to set additional contenttypes, require("kulala.parser.jsonpath") fails:
pathresolver = require("kulala.parser.jsonpath").parse
for me throws as soon as I add it to one of the contenttypes
Fehler beim Ausführen von "/Users/me/.config/nvim/init.lua":
Failed to load `plugins.kulala`
/Users/me/.config/nvim/lua/plugins/kulala.lua:33: module 'kulala.parser.jsonpath' not found:
	no field package.preload['kulala.parser.jsonpath']
	cache_loader: module 'kulala.parser.jsonpath' not found
	cache_loader_lib: module 'kulala.parser.jsonpath' not found
	no file './kulala/parser/jsonpath.lua'
	no file '/Users/me/dev_other/neovim/.deps/usr/share/luajit-2.1/kulala/parser/jsonpath.lua'
	no file '/usr/local/share/lua/5.1/kulala/parser/jsonpath.lua'
	no file '/usr/local/share/lua/5.1/kulala/parser/jsonpath/init.lua'
	no file '/Users/me/dev_other/neovim/.deps/usr/share/lua/5.1/kulala/parser/jsonpath.lua'
	no file '/Users/me/dev_other/neovim/.deps/usr/share/lua/5.1/kulala/parser/jsonpath/init.lua'
	no file './kulala/parser/jsonpath.so'
	no file '/usr/local/lib/lua/5.1/kulala/parser/jsonpath.so'
	no file '/Users/me/dev_other/neovim/.deps/usr/lib/lua/5.1/kulala/parser/jsonpath.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
	no file './kulala.so'
	no file '/usr/local/lib/lua/5.1/kulala.so'
	no file '/Users/me/dev_other/neovim/.deps/usr/lib/lua/5.1/kulala.so'
	no file '/usr/local/lib/lua/5.1/loadall.so'
# stacktrace:
  - ~/.config/nvim/lua/plugins/kulala.lua:33 _in_ **load**
  - ~/.config/nvim/lua/user/lazy.lua:28
  - ~/.config/nvim/init.lua:1

**Comment by Grueslayer** [comment]
Seems you are loading Kulala lazy/very lazy e.g. by command. If so, you are unable to use lua functions as callback from a module not already loaded.
