### ISSUE TITLE
Getting duplicate entries with set_selected_env()

### ISSUE THREAD

**Issue by sanchay9** [mistweaverco/kulala.nvim#271]
Hi,
I'm getting duplicate entries on calling `require('kulala').set_selected_env()` after some recent update

![image](https://github.com/user-attachments/assets/779df278-3990-4deb-802d-b84f1b606618)

- My http-client.env.json

```json
{
  "$schema": "https://raw.githubusercontent.com/mistweaverco/kulala.nvim/main/schemas/http-client.env.schema.json",
  "$shared": {
    "$default_headers": {
      "Content-Type": "application/json",
      "Accept": "application/json"
    }
  },
  "dev": {
    "core_url": "http://localhost:8080"
  },
  "uat": {
    "core_url": "https://abc.com"
  },
  "cug": {
    "core_url": "https://abc.com"
  },
  "prod": {
    "core_url": "https://abc.com"
  }
}
```

**Comment by gorillamoe** [comment]
What does `:checkhealth kulala` or `:lua require("kulala").version()` say? seems like you're on an old version?

**Comment by sanchay9** [comment]
![image](https://github.com/user-attachments/assets/4f76fc72-7203-4e87-a358-2532a1f3a487)

![image](https://github.com/user-attachments/assets/6355dada-83c8-4d8c-9684-c2d993a4081f)

I'm using updated Neovim and kulala.nvim both

**Comment by gorillamoe** [comment]
Thanks for catching this bug :bug: !
