### ISSUE TITLE
[Feature] Search for Requests

### ISSUE THREAD

**Issue by skela** [mistweaverco/kulala.nvim#275]
Search is pretty handy, would be nice if it could open a telescope fuzzy finder, then list out all requests inside any .http files in the current folder (or in a subfolder of your choosing).

The require("kulala").search() isnt all that useful though, it just lists out the .http files in the current working directory.
Would it be an idea to replace the search function or extend it so you could alternatively search and pick a particular request (and be able to have it search for more than the current working directory) ?

**Comment by gorillamoe** [comment]
> Would it be an idea to replace the search function so you could alternatively search and pick a particular request

I think that would make it an ideal replacement!
