### ISSUE TITLE
Put scripts in a different (fs) location

### ISSUE THREAD

**Issue by willruggiano** [mistweaverco/kulala.nvim#282]
For those of us that have our plugins installed in a read-only filesystem.

After updating the plugin a few days ago, I get the error shown in the screenshot below. Courtesy of `ensure_dir_exists` in fs.lua. Ideally this stuff would go in `stdpath('data')` or `stdpath('cache')`

![screenshot-2024-10-10T09:15:53-07:00](https://github.com/user-attachments/assets/75f87dd6-bb26-42a5-9296-323be5d2b684)

**Comment by gorillamoe** [comment]
Yes, we used `stdpath` before, but it was causing issues with windows filepaths :cry: .

Seems that the returned value from that does not have the correct path separator for windows :thinking: so this was an attempt to work around that.

Strage thing you even have that error message, are you using scripts?

**Comment by willruggiano** [comment]
I am not, no. Didn't even know about them :D

**Comment by gorillamoe** [comment]
Ah, shit the "fix" in main won't work either, because everything is happening in the tmp dir in kulala atm.. I have to overhaul that part completely I guess.
