### ISSUE TITLE
Assign a "kulala" filetype

### ISSUE THREAD

**Issue by rachartier** [mistweaverco/kulala.nvim#288]
Hello,
Thank you very much for this plugin.

I was wondering if it’s possible to assign a custom file type like `kulala-<ft>` to the created buffer (`kulala-json`, `kulala-xml`...) and link it to the corresponding filetype in treesitter with [vim.treesitter.language.register()](https://neovim.io/doc/user/treesitter.html#vim.treesitter.language.register())

This way, it would be possible to use other plugins, such as Edgy, or set up autocmd events for it. With `vim.treesitter.language.register`, it will keep it's code highlights and all.

Thank you for your consideration.

**Comment by Grueslayer** [comment]
You can set your preferred filetype for each Content-Type in the config, the registration of that new one in treesitter is than on your own.

**Comment by rachartier** [comment]
Thanks!
