### ISSUE TITLE
Inject params for cURL commands

### ISSUE THREAD

**Issue by franroaxeridia** [mistweaverco/kulala.nvim#29]
Hi there! really cool plugin!
I wonder if you are thinking about making it possible to add params to the curl command like "--insecure", to work

**Comment by gorillamoe** [comment]
Great enhancement. I'll add it later on.

**Comment by gorillamoe** [comment]
The first version of this will add globally added flags via the options table in the setup function.

Once we finished #18, we can also add them on a per request basis.
