### ISSUE TITLE
Loading Authorization Bearer token from file adds header to payload

### ISSUE THREAD

**Issue by timjstewart1024** [mistweaverco/kulala.nvim#290]
I am trying to store an OAuth token obtained from an API in a file so that I can make multiple requests to the API with the same token.

I have stored my token in a file named `token.txt` that is in the same directory as my .http files.

token.txt contains (not the real token):

```text
VYhTGZlXm3uabababababcdefgw5BS
``` 

Note: There is **no** new line character in the file.

My `.http` file is as follows:

```text
# @file-to-variable TOKEN ./token.txt
POST https://httpbin.org/post
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "user_id": "4",
}
```

When I send this request, the response that comes back from httpbin.org is:

```
{
  "args": {},
  "data": "Content-Length: 23\r\n\r\n{\r\n  \"user_id\": \"4\",\r\n}",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "*/*",
    "Authorization": "Bearer VYhTGZlXm3uabababababcdefgw5BS",
    "Content-Length": "45",
    "Content-Type": "application/json",
    "Host": "httpbin.org",
    "User-Agent": "kulala.nvim/4.3.0",
    "X-Amzn-Trace-Id": "Root=1-67103b21-61dcc69575c88c2615719356"
  },
  "json": null,
  "origin": "71.205.212.216",
  "url": "https://httpbin.org/post"
}
```

Notice that the `data` field contains the `Content-Length` header.

If I replace:

```
Authorization: Bearer {{TOKEN}}
```

with:
 
```
Authorization: Bearer VYhTGZlXm3uabababababcdefgw5BS
```

and send the request, I get a response that has valid JSON in the `data` field:

```
{
  "args": {},
  "data": "{\r\n  \"user_id\": \"4\",\r\n}",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "*/*",
    "Authorization": "Bearer VYhTGZlXm3uabababababcdefgw5BS",
    "Content-Length": "23",
    "Content-Type": "application/json",
    "Host": "httpbin.org",
    "User-Agent": "kulala.nvim/4.3.0",
    "X-Amzn-Trace-Id": "Root=1-67103b7d-5221b80d2ce0b7802d8b56a8"
  },
  "json": null,
  "origin": "71.205.212.216",
  "url": "https://httpbin.org/post"
}
```

Is this feature currently supported?  Am I doing something wrong?

Thanks in advance!

**Comment by gorillamoe** [comment]
I haven't tried myself, but your json is invalid, can you try:

```http
# @file-to-variable TOKEN ./token.txt
POST https://httpbin.org/post
Authorization: Bearer {{TOKEN}}
Content-Type: application/json

{
  "user_id": "4"
}
```

**Comment by Grueslayer** [comment]
@gorillamoe As of some commit the CMD line isn't written anymore to a file when debug=true. Maybe you can rewrite the REQUEST_FILE at the end of parser/init.lua as res will contain the cmd table as well.

When I use the request from above (with or w/o comma) it produces something like this (empty body) from pastebin

```http
HTTP/1.1 200 OK
Date: Thu, 17 Oct 2024 06:40:52 GMT
Content-Type: application/json
Content-Length: 389
Connection: keep-alive
Server: gunicorn/19.9.0
Access-Control-Allow-Origin: *
Access-Control-Allow-Credentials: true


{
  "args": {},
  "data": "",
  "files": {},
  "form": {},
  "headers": {
    "Accept": "*/*",
    "Authorization": "Bearer VYhTGZlXm3uabababababcdefgw5BS",
    "Host": "httpbin.org",
    "User-Agent": "kulala.nvim/4.3.0",
    "X-Amzn-Trace-Id": "Root=1-6710b174-49de8e4235c623217534a816"
  },
  "json": null,
  "origin": "178.142.31.150",
  "url": "https://httpbin.org/post"
}
```

`data` is empty (what ever httbin is doing) BUT curl request looks fine:

```json
  "cmd": [
    "curl",
    "-s",
    "-D",
    "C:\\Users\\userx\\AppData\\Local\\Temp\\nvim\\kulala/headers.txt",
    "-o",
    "C:\\Users\\userx\\AppData\\Local\\Temp\\nvim\\kulala/body.txt",
    "-w",
    "@C:/Users/userx/AppData/Local/nvim-data/lazy/kulala.nvim/lua/kulala/utils/..\\parser\\curl-format.json",
    "-X",
    "POST",
    "--data",
    "{\r\n  \"user_id\": \"4\"\r\n}",
    "-H",
    "Authorization:Bearer VYhTGZlXm3uabababababcdefgw5BS\n",
    "-H",
    "Content-Type:application/json",
    "-A",
    "kulala.nvim/4.3.0",
    "--cookie-jar",
    "C:\\Users\\userx\\AppData\\Local\\Temp\\nvim\\kulala/cookies.txt",
    "https://httpbin.org/post"
  ],

```

BTW: Can we make the Skript `-w` using a correct Windows path with backslash?

**Comment by Grueslayer** [comment]
@timjstewart1024 Does your token.txt file contain a Linefeed at the end of the file? If you've created the file with vim you need to

```vim
set noeol
set nofixeol
```

to prevent vim from adding a new line when writing the file.

**Comment by timjstewart1024** [comment]
@gorillamoe thanks for pointing out the invalid JSON.  I pasted the request you sent into my file and re-ran it.  I'm still getting the Content-Length header in the data field.

Running the token.txt file through `hexdump` showed that there was a `000a` at the end.

To prevent vim from adding the new line I ran: 

```
:set binary
:set noeol
:w
```

Thanks for such an awesome tool!
