### ISSUE TITLE
Not working on Windows 11 or do I have skill issues???

### ISSUE THREAD

**Issue by nadvorniktom** [mistweaverco/kulala.nvim#297]
Specs:
- OS Name: Microsoft Windows 11 Pro
- NVIM v0.10.2
- cURL v8.10.1
- kulala v4.3.0

Problem:
When calling :lua require('kulala').run() I'll see emojis of hourglass and a tick or a cross if request failed or succeeded.
But that's it.
No request body will be shown.
When I call :messages I will see this:
_...gram Files/Neovim/share/nvim/runtime/lua/vim/_system.lua:244: ENOENT: no such file or directory
stack traceback:
	[C]: in function 'error'
	...gram Files/Neovim/share/nvim/runtime/lua/vim/_system.lua:244: in function 'spawn'
	...gram Files/Neovim/share/nvim/runtime/lua/vim/_system.lua:335: in function 'system'
	...nvim-data/lazy/kulala.nvim/lua/kulala/formatter/init.lua:8: in function 'format'
	.../Local/nvim-data/lazy/kulala.nvim/lua/kulala/ui/init.lua:289: in function 'show_body'
	.../Local/nvim-data/lazy/kulala.nvim/lua/kulala/ui/init.lua:223: in function 'callback'
	...Local/nvim-data/lazy/kulala.nvim/lua/kulala/cmd/init.lua:136: in function <...Local/nvim-data/lazy/kulala.nvim/lua/kulala/cmd/init.lua:103>_
	
**Note that I have _system.lua exactly on this path so it's not like this file or folder structure doesn't exist.**
I don't know how to investigate this problem further.

Is it a Nvim problem, kulala problem or a me problem?
Would greatly appreciate any help.

**Comment by Grueslayer** [comment]
Hi,

Win11 is my daily system.

This error occures while formatting the result. For JSON you need `jq` and XML or HTML you need `xmllint` which kulala tries to find in setup process. Only when those can be found formatting will be done.

It seems you manually set `contenttypes` in your `kulala.setup()` call and references on any not existing program for formatters.

Please post your complete setup of kulala for further inspection.

**Comment by nadvorniktom** [comment]
Hi, thanks for quick response.

I'm currently running lazyvim and had option of adding extras: rest - which is adding Kulala.
I haven't made any changes to this config.
Lazyvim config of kulala can be found here:
https://lazyvim.github.io/extras/util/rest

Also I have jq installed so that shouldn't be a problem.

**Comment by Grueslayer** [comment]
1. Do you use "neovide", there is a known problem with changing PATH which is not forwarded to the separate nvim process.
- if so, please try `nvim` in a cmd terminal (without neovide)
2. Where is `jq` installed?
- Is it in normal Windows PATH?
- What does `where jq` say when starting in cmd terminal?
3. What is the following output when starting from neovim
```vim
:lua print(vim.inspect(require("kulala.config").get().contenttypes))
```

**Comment by Grueslayer** [comment]
4. This should also produce the same error when called from neovim (as `jq` is not found in path)

```vim
:lua print(vim.inspect(vim.system({ 'jq' })))
```

**Comment by nadvorniktom** [comment]
1. I'm not using neovide. I'm running nvim in wezterm 
2. I'm able to call/use jq in from terminal. Installed using winget and added manualy to PATH.
3. (Un)fortunately I'm on vacation right now and I didn't bring my PC so I will try those lua prints on Monday. And will get back to you afterwards.

Thanks again for responding and trying to help me out.

**Comment by nadvorniktom** [comment]
3. The output is this:

  ["application/json"] = {
    formatter = { "jq", "." },
    ft = "json",
    pathresolver = <function 1>
  },
  ["application/xml"] = {
    formatter = { "xmllint", "--format", "-" },
    ft = "xml",
    pathresolver = { "xmllint", "--xpath", "{{path}}", "-" }
  },
  ["text/html"] = {
    formatter = { "xmllint", "--format", "--html", "-" },
    ft = "html"
  }

4. The output is this:

**Comment by nadvorniktom** [comment]
The issue was caused by using $env:LOCALAPPDATA\nvim-data\mason\packages\jq\jq-windows-amd64.exe.
After installing jq using winget, adding it to PATH ($env:LOCALAPPDATA\Microsoft\WinGet\Packages\jq) and removing mason's jq the issue was resolved and everything works normally.

**Comment by nadvorniktom** [comment]
Thanks @Grueslayer for figuring that out.
It's a shame there isn't a better error message than: .../nvim/runtime/lua/vim/_system.lua:244: ENOENT: no such file or directory.
I've had no idea that there could be an issue with jq from that message.

**Comment by Grueslayer** [comment]
@nadvorniktom This is a nvim / lua implementation problem. If you write `where jq` in the windows cmd promt it will search for all executable programs (like `jq.exe` / `jq.bat` / `jq.cmd`) also the vim function called from lua `vim.fn.executable` behaves the same and finds your `jq.cmd` and therefore it is configured to use that.

BUT `vim.system` also checks the first parameter and does NOT use the same search parameters. So if you have to define the compete name `jq.cmd` in the kulala config.

This is a neovim bug and needs to be addressed by thy neovim team, I'm sorry.
