### ISSUE TITLE
The CJK string in the json request body is incorrectly replaced with `[[binary file skipped]]`

### ISSUE THREAD

**Issue by Urie96** [mistweaverco/kulala.nvim#309]
![image](https://github.com/user-attachments/assets/f68b0d83-3bac-40be-81d3-0e7cd700fbf4)

req:
```http
POST http://localhost:7890
content-type: application/json

{
  "index_doctor_name": [
    "你好"
  ]
}
```

**Comment by gorillamoe** [comment]
Does this happen on the main branch?

**Comment by Urie96** [comment]
> Does this happen on the main branch?

No. Sorry to bother you. I'm closing it.
