### ISSUE TITLE
Support dotenv 

### ISSUE THREAD

**Issue by fpohtmeh** [mistweaverco/kulala.nvim#31]
[.env](https://www.npmjs.com/package/dotenv) is another popular format for environment variables.
Could you please add the support of the format?

**Comment by gorillamoe** [comment]
Can you elaborate on what exactly is missing? If it isn't already working it might be a regression. I added .env support quite early in the development. Only the multiline is not supported (yet).

**Comment by fpohtmeh** [comment]
Oops, sorry. I checked the default configuration in README and found only env.json. Now I see that .env is supported too 💪.
It may be helpful if you mention dotenv in the README too. Thank you!
