### ISSUE TITLE
Already escaped value of query is escaped again

### ISSUE THREAD

**Issue by Urie96** [mistweaverco/kulala.nvim#316]
![image](https://github.com/user-attachments/assets/c637e06c-5543-4dd3-ae98-878d4c3a655f)

**Comment by Grueslayer** [comment]
This seems no bug. Query parameters will be escaped like in VSCode Rest Client. There would be no 100% chance to know what the user inputs and where a conversion is needed and where it is already done.

**Comment by Urie96** [comment]
Actually VSCode Rest Client works well, so I temporarily back to VSCode to continue my request. After some simple tests, I guess that as long as the value has a `%` then it will not be escaped by VSCode Rest Client.
![image](https://github.com/user-attachments/assets/aa439b64-f189-4f3b-8503-684dd0049a9b)

**Comment by Grueslayer** [comment]
Still i am not think that’s a good way. What is about % in a content, how should you determine if  user has already encoded the text or just want to transmit a %. Maybe you must also differentiate between text directly written in the http buffer and  “normal” variables and request variables obtaining their content from responses.

Personally I always would expect the query parameters unescaped / plain text.

**Comment by Urie96** [comment]
> Personally I always would expect the query parameters unescaped / plain text.

This only applies to manually constructed URLs. However, the curl generated from Chrome or other packet capture tools is often escaped, importing it directly into kulala will send unexpected request, but `curl` command works because it does not escape the query. 
Chrome and VSCode Rest Client behave the same way, they will not escape `%` to `%25`, but will escape `你好` to `%E4%BD%A0`. In most cases, it doesn't matter if the query parameter is not escaped, the server's lib can often parse it correctly, just like how kulala parses it.
> Maybe you must also differentiate between text directly written in the http buffer and “normal” variables and request variables obtaining their content from responses.

It's rare to include `{{name}}` in HTTP, but it's common to include escapes in queries.

**Comment by Grueslayer** [comment]
I've tested VSCode Rest Client and the result is:

if something matches '%[0-9a-f][0-9a-f]' if will be taken as already encoded, everything else will be escaped.

That means 

- `John%20Doe` will become `John Doe`
-  but `Kent%ABC` will fail as %AB is not a valid char without next missing 8-bit
- `Kent%XYC` is `Kent%XYC` !!!

So as long this is directly written in the URL part of the HTTP request line, I can accept this (for copy&paste from outside)

**BUT**

VSCode Rest Client does this also for variables:

If you define a variable with `%` or get a content by JSON which contains a `%` and want to forward this to a query parameter you are lost (as long the next two chars are hexidecimal). This is a break in the functionality!

Further if the JSON delivers you a complete URL and you use that to make a call

```http
GET {{values.response.body.json.url}} HTTP/1.1
```
and we currently escapes these a second time, it's also wrong.
