### ISSUE TITLE
Stopped to work for Windows

### ISSUE THREAD

**Issue by fpohtmeh** [mistweaverco/kulala.nvim#34]
I tried the plugin after the Reddit announcement. It worked like a charm.

Today I got this error when I ran `:lua require('kulala`)`
![image](https://github.com/mistweaverco/kulala.nvim/assets/147282455/d5cb48ab-38e8-493b-84e8-80cd9cdca361)

And ``:lua require('kulala`).run()` hangs now

**Comment by gorillamoe** [comment]
Are you on the latest version?

**Comment by fpohtmeh** [comment]
I updated it again, and the issue has gone. Thank you for the intensive work!

Just for case, adding a broken and fixed versions to this response
![image](https://github.com/mistweaverco/kulala.nvim/assets/147282455/9ff7d6bc-fa0c-4e19-89b7-85c7e3fe94f3)
