### ISSUE TITLE
Icons settings reset after toggle headers

### ISSUE THREAD

**Issue by darteil** [mistweaverco/kulala.nvim#37]
Preview:

https://github.com/mistweaverco/kulala.nvim/assets/31193144/90641187-9efc-4a59-b6dd-c1e5ba20114d

I was able to fix this after making changes to the function toggle_headers in file /lua/kulala/ui/init.lua:124

from
```
CONFIG.set_config(CFG)
```
to
```
CONFIG.set_config(CONFIG.get_config())
```
But I'm not sure if this is the right decision

**Comment by gorillamoe** [comment]
Should be fixed on the latest commit on main :+1: Thanks for reporting this issue.
