### ISSUE TITLE
Kulala blocks/freezes neovim waiting for http response

### ISSUE THREAD

**Issue by coltorl** [mistweaverco/kulala.nvim#41]
Hello, I just started using the plugin and I think it's really neat! When I make a simple GET request with a debugger running with a breakpoint on the entrance to the GET function, the whole neovim client freezes. I believe it is because of a blocking cmd run here: https://github.com/mistweaverco/kulala.nvim/blob/939025ce5357d1d534a01faf454e012d87874f59/lua/kulala/cmd/init.lua#L9

The command blocks the neovim client until the response is returned, however because I have dap running in the same frozen client, I can't unbreak out of the breakpoint so it just stays frozen.

I fixed this locally and will open a PR for you to review/improve upon.

Thanks again!

**Comment by gorillamoe** [comment]
Awesome improvement! 💪🏾
