### ISSUE TITLE
Unable to run HTTP request for Salesforce API

### ISSUE THREAD

**Issue by ognjen-vuceljic** [mistweaverco/kulala.nvim#43]
Hi there @gorillamoe ,

I came across this interesting plugin, so I wanted to try it out.

In my current repo, I have a bunch of `.http` files that I use for various types of integration tests. 

I picked one that I was able to run in VS Code via Rest-Client extension, which has the following structure (details have been obfuscated/dummied)

`POST https://this_is_client_instance.salesforce.com/services/oauth2/token?grant_type=password&client_id=here_goes_client_id&client_secret=here_goes_client_secret&username=mysfusername&password=mysfpasswordplustoken HTTP/1.1`

It's a very simple POST request that, when run via VS Code, produces the following results (Status = 200 OK)

![Screenshot 2024-07-11 at 01 11 40](https://github.com/mistweaverco/kulala.nvim/assets/102177460/a22e67c5-088d-4414-88f8-eee368702a82)

However, when I run it in neovim, as per instructions, I get the following error(s):

![Screenshot 2024-07-11 at 01 13 59](https://github.com/mistweaverco/kulala.nvim/assets/102177460/44b8d09d-474b-4748-a246-6fec43a91133)

Notes:

- I have not set up any environments so far
- my file has `.http` extension, and I have everything from the prerequisites section installed (correct Neovim version, `jq`, `curl`, etc.)

I appreciate the fact that, most likely, my plugin config is wrong, so I am happy to have some guidance on this one.

Thanks, and have a great day!

**Comment by gorillamoe** [comment]
Hey there, thanks for raising this issue.

This might be due to the fact, that kulala itself doesn't add default headers like the vscode Rest-Client.

I took a peek at the source and it seems, that it adds at least one header by default.

I'll let implement something similar for kulala, but will make it opt-in.

In the meantime, you can try to add these headers via the http files.

```http

POST https://this_is_client_instance.salesforce.com/services/oauth2/token?grant_type=password&client_id=here_goes_client_id&client_secret=here_goes_client_secret&username=mysfusername&password=mysfpasswordplustoken HTTP/1.1
content-type: application/json
accept: application/json
```

**Comment by gorillamoe** [comment]
Okay, that might not be the issue :-1: 

I tried to reproduce it and it seems that the Treesitter Grammar is failing here again :sob: 

So, I'm already working on a complete rewrite #18 . But until then, try this to leave out the optional HTTP Version like so:

```http
POST https://httpbin.org/post?grant_type=password&client_id=here_goes_client_id&client_secret=here_goes_client_secret&username=mysfusername&password=mysfpasswordplustoken

```

**Comment by ognjen-vuceljic** [comment]
Thank you @gorillamoe , removing optional HTTP version worked, so I get 200 OK :)

I need to figure out how to get the response autoformatted to JSON - at the moment it recognizes it as plain text, but that's fine, I will look into the plugin documentation.

**Comment by gorillamoe** [comment]
Just add a header like this:

```
accept: application/json
```

This will trigger a formatter

**Comment by ognjen-vuceljic** [comment]
Thank you very much @gorillamoe , that works.

We can close this issue, or link it with #18 (will leave that up to you).
