### ISSUE TITLE
HTTP Response Code not visible on response

### ISSUE THREAD

**Issue by ognjen-vuceljic** [mistweaverco/kulala.nvim#48]
Hi @gorillamoe,

thanks for making continuous improvements!

I've just installed version `2.0.0` and it works pretty well!

There is one thing I've noticed (unless I am missing something in config) -  HTTP Response codes are not visible anywhere in the response. 

Here's one 401 example from the request that should obtain Bearer token from a Salesforce environment:

![Screenshot 2024-07-12 at 00 57 27](https://github.com/user-attachments/assets/75bac094-ce9f-43f6-a99f-c22f0aa0be06)

JSON response is there, message is clearly visible, but I can't see the 401 anywhere.

In the screenshot, I have included an idea about where the response code can be placed. Appreciating the fact that such UI adjustment might not be easy to make, and I am personally fine with any adjustment, as long as HTTP response code can be clearly and easily visible.

If the feature is already there, I apologize - I'll just need some guidance regarding setting it up in my plugin setup 😄 

Thank you!

**Comment by gorillamoe** [comment]
The response headers should be already available, you can toggle them via

```lua
require("kulala").toggle_view()
```

https://kulala.mwco.app/#/public_methods?id=toggle_view

**Comment by ognjen-vuceljic** [comment]
Great, thank you very much @gorillamoe
