### ISSUE TITLE
Change buffer type to `json` for json only requests.

### ISSUE THREAD

**Issue by Redoxahmii** [mistweaverco/kulala.nvim#51]
When sending a request with kulala when in an http file there is option to toggle headers and body but if the default behavior is set not to show them is there someway we can create a buffer which has `ft` set to `json` by default.
Reason for asking this is i have my own plugin [json-to-types.nvim](https://github.com/Redoxahmii/json-to-types.nvim) which i use for generating types and i have limited it to only run on files with `ft=json`.

I planned on writing a rudimentary request system to send requests like kulala which would then convert the types as well but i like this plugins approach better then re-inventing the wheel.
Having this option would make it more easier and friction less to use in tandem with the plugin and also would provide the treesitter syntax highlighting when looking at json objects.
Could be provided as optional to if someone wants to opt in.

**Comment by gorillamoe** [comment]
Idk if I understand you correctly, but the if you have a accept: application/json header in your request, the ft of the response buffer should be json, no?

**Comment by Redoxahmii** [comment]
I was sending the request without the header :smiling_face_with_tear:
The buffer that is created cannot be used with my plugin cause it requires the buffer to be saved so i guess i would still have to copy paste it to a separate file.
Thank you for the info.

**Comment by gorillamoe** [comment]
Maybe we can work something out. I'm working on a draft where you can postprocess the response with external commands e.g. auto save to a file, export it to a env var and so on. The response of a successful request is always stored to disk, so you can also read from that file if this might work for you. I'm currently charging my car and then I need to shop some groceries, but we can have a chat about that in discord if you like. Just join the discord server mentioned in the readme.

**Comment by gorillamoe** [comment]
I mean if you simply want to be able to save the response. Simply do `:set buftype=""` this will make so that the buffer can be saved with `:saveas filename.json`

**Comment by Redoxahmii** [comment]
Access to post process the response with external commands could prove useful. I also save file on disk for the response which later gets deleted but that file is saved in the same folder as my plugin. Maybe reading it from the `/.local/state` for nvim could make it more centralized for reading.

**Comment by Redoxahmii** [comment]
I currently just dump the file inside the plugin folder instead of using the `/tmp/{plugin_name}` by using `vim.fn.stdpath` to get the dir for my plugin and doing it the **proper way**

**Comment by gorillamoe** [comment]
Can you open another issue with a proposed integration? Maybe the thing I'm working on can suffice.

I'm working on an opt in way to run pre- postprocess exposed API hooks + the ability to trigger external commands pre- and post processing.

**Comment by gorillamoe** [comment]
The thing would look something like this:

```lua

require("kulala.hooks.request").after(function(ft, body)
  print(body)
end)
