### ISSUE TITLE
Import and export curl command

### ISSUE THREAD

**Issue by guruor** [mistweaverco/kulala.nvim#67]
Thank you so much for developing this plugin, I have been monitoring the dev work on it since the first release.

One thing keeping me from migrating from rest.nvim to this plugin is lack of curl export. It would be great to have an option to copy the curl command for HTTP request under cursor. Even latest rest.nvim doesn't have that feature but it used to have feature named `RestNvimPreview` in older version, which I [forked](https://github.com/guruor/rest.nvim) long ago.

We can plan for dedicated import-export module to support multiple format but I think `curl` export as initial point will be a good start.

**Comment by gorillamoe** [comment]
Thanks for coming up with this idea. I think this will be a great addition.

**Comment by gorillamoe** [comment]
See: https://kulala.mwco.app/docs/public_methods/#copy

**Comment by guruor** [comment]
That was quick, Thanks 🙇‍♂️ .
Will try it today.
