### ISSUE TITLE
How can I change the position of the response window

### ISSUE THREAD

**Issue by luisparedes-nomad** [mistweaverco/kulala.nvim#7]
In the documentation a gif is shown where the response opens on the right side but for me it opens on the left side, how can I configure it?
![image](https://github.com/mistweaverco/kulala.nvim/assets/173492384/d294af05-9534-4724-aaf5-65d318417491)

**Comment by gorillamoe** [comment]
You should be able to configure that in your neovim configuration, either globally or just for http files.

```lua
vim.opt.splitright = true
```

**Comment by gorillamoe** [comment]
Hey @luisparedes-nomad, does this help? Can we close this issue?

**Comment by luisparedes-nomad** [comment]
it works, thx
