### ISSUE TITLE
Possibility to use env variables in the HTTP request instruction

### ISSUE THREAD

**Issue by adr-mo** [mistweaverco/kulala.nvim#70]
Hi,

I've been using kulala for several days now and it is awesome ! I got rid of Bruno as it perfectly fits my workflow 👍🏻 
There is still something that could be great, I don't know if it is a feature request or a bug but I can't use an env variable in the http file in the URL definition.

![image](https://github.com/user-attachments/assets/ce79d34f-7b5f-408d-9ffd-b7690a1a8367)

Credentials were obfuscated so you can get an idea of what I mean.

It is important to mention that USERNAME and PASSWORD are perfectly working and also the dymamic setting of AUTH_TOKEN.

My configuration is quite basic

```
❯ cat .config/nvim/lua/plugins/kulala.lua
return {
    {
        'mistweaverco/kulala.nvim',
        lazy = false,
        config = function()
            require('kulala').setup({})
        end
    }
}
```
Thanks 💯 

**EDIT**

I've also tried to remove the URL from the POST instruction and pass the `Host: {{URL}}` header but got the same result 👍🏻

**Comment by gorillamoe** [comment]
It should work. I think you need to  remove the `http://` either from the env file or from the http file or it fails because I tried to connect to http://http://localhost:port

**Comment by gorillamoe** [comment]
Just FYI, for that simple query of the token, you can also use the built-in parser and not rely on the external jq command. This should be quicker and easier to read:

```http
POST {{HOST}}/auth/login
# @env-json-key AUTH_TOKEN access_token

{
  "email": "{{ADMIN_EMAIL}}",
  "password": "{{ADMIN_PASSWORD}}"
}
```

**Comment by adr-mo** [comment]
Hi @gorillamoe thanks for the quick answer.
I've tested with your indications and it works like a charm 💪🏻 

Thank you very much 🐼 

Regards

Adrien
