### ISSUE TITLE
Add more details to repo README

### ISSUE THREAD

**Issue by nipuna-perera** [mistweaverco/kulala.nvim#71]
I am behind a corporate firewall and for some reason I can't access the docs site. For such use cases, it would help to have at least some fundamental details on the README of the repository. 

I suspect something is default blocking the site but it doesn't tell me what. As a workaround, I can try building the docs site myself locally.

**Comment by gorillamoe** [comment]
I need to check how we might achieve that without much overhead. Keeping the docs site and Readme in sync is a chore.

**Comment by nipuna-perera** [comment]
I totally understand. If you want to get the website sorted so it's allow
listed in corp environments that would work too. I am happy to test things
for you.

**Comment by gorillamoe** [comment]
You could check, if it has to do with the tld, so checking if https://get.app/ works for you could help.

**Comment by gorillamoe** [comment]
Could you check @nipuna-perera ?

**Comment by nipuna-perera** [comment]
I am on vacation and don't have access to the work VPN. I will test when I
get back.

**Comment by nipuna-perera** [comment]
Actually! I can access kulala.nvim now. IDK what changed. I'll close this. Thanks for looking into it :)
