### ISSUE TITLE
[Feature Request] Convert to HTTP from curl

### ISSUE THREAD

**Issue by LintaoAmons** [mistweaverco/kulala.nvim#78]
When I using IDEA's HTTP tool, one of the most useful features is the curl compatibility.

When copy a curl into the buffer, it will automatically generate the HTTP format request and put the original curl command as comment above the HTTP request.

And it can allow you to copy a HTTP format request as curl, sometimes it is very convenient and smooth

**Comment by gorillamoe** [comment]
> And it can allow you to copy a HTTP format request as curl, sometimes it is very convenient and smooth

You can copy it as cURL command: https://kulala.mwco.app/docs/public_methods#copy

> When copy a curl into the buffer, it will automatically generate the HTTP format request and put the original curl command as comment above the HTTP request.

This will be a really cool addition.

**Comment by gorillamoe** [comment]
Related #186

**Comment by gorillamoe** [comment]
> When copy a curl into the buffer, it will automatically generate the HTTP format request and put the original curl command as comment above the HTTP request.

Available in `main` due to the nice work done in #186 by @vyskocilm.
