### ISSUE TITLE
Dynamically setting environment variables based on response Headers

### ISSUE THREAD

**Issue by renata-amutio-herrero** [mistweaverco/kulala.nvim#87]
Is it possible to set dinamically environment variables using the headers of the response?

**Comment by gorillamoe** [comment]
This is currently not possible (in fact it would be possible, but pretty complicated..), but once we have #66, it's pretty easy.

I can totally see me implementing an interim solution in the meantime.

If you can't wait and need a way to have this right away, you can look at 
https://kulala.mwco.app/docs/usage/dynamically-setting-environment-variables-based-on-response-json#with-external-command

Where you substitute jq with any homemade script you want.

The script needs to take the contents of `.local/share/nvim/tmp/kulala/headers.txt` and parse them and return the header you want.
