### ISSUE TITLE
Kulala://ui window dont respawn when he is closed for the first time it need to close folder globally to get respawn

### ISSUE THREAD

**Issue by Myhed** [mistweaverco/kulala.nvim#9]
He, when i close the window buff named kulala://ui and re run the request the buff kulala://ui dont re-appear.

When i close globally folder with nvim and then reopen with it that works again.

**Comment by gorillamoe** [comment]
Yep, that is something I'm working on. I'll keep you posted.

**Comment by Myhed** [comment]
Okay, i just tell you, when you do a :bwipeout it call nvim_buf_del function and it works when you use it. if it can help you
